package constants

// ValidEventTypes lists all acceptable event_type values for RunSignup API
var ValidEventTypes = map[string]bool{
	"running_race":       true,
	"virtual_race":       true,
	"nonprofit_event":    true,
	"running_only":       true,
	"walking_only":       true,
	"race_walk":          true,
	"wheelchair":         true,
	"triathlon":          true,
	"duathlon":           true,
	"bike_race":          true,
	"bike_ride":          true,
	"mountain_bike_race": true,
	"gravel_grinder":     true,
	"fundraising_ride":   true,
	"trail_race":         true,
	"open_course_trail":  true,
	"ultra":              true,
	"hike":               true,
	"obstacle_course":    true,
	"adventure_race":     true,
	"swim":               true,
	"swim_run":           true,
	"aqua_bike":          true,
	"ski":                true,
	"paddle_sports":      true,
	"disc_golf":          true,
	"clinic":             true,
	"expo":               true,
	"skate":              true,
	"ruck":               true,
	"other":              true,
}
